GEMINI_API_KEY=
YOUTUBE_API_KEY=AIzaSyDbkFoz0-6cj2AR8cXGJVci2RPK_0oAxos
TAVILY_API_KEY=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
ELEVENLABS_API_KEY=9dcae6842f3e53c4f885e4dcf30bf5635e8284c41df98d93f8b432b5f4383e90
ACRCLOUD_ACCESS_KEY=1d2662be97a95de33ae5a111a6a895ff
ACRCLOUD_ACCESS_SECRET=BFf6SmDETpRrJck7Gw75HUAQTuT2bUhWF4rUkRjM
NEXUS_BASE_URL=https://mausand2499--jarvoice-nexus-api-nexusserver-serve-dev.modal.run
NEXUS_WS_HOST=mausand2499--jarvoice-nexus-api-fastapi-server-dev.modal.run
